### ISSUE TITLE
"Config" does not work, "use" does

### ISSUE THREAD

**Issue by MagnusEnger** [bigpresh/Dancer-Plugin-NYTProf#13]
I tried to enable this plugin using the "config" method, as described in the POD, but it did not work. /nytprof gave a 404 and no data was gathered in the directory indicated by the "profdir" setting. 

Including "use Dancer::Plugin::NYTProf;" in the app itself (as described here: http://advent.perldancer.org/2011/9) did work. 

Tested with Dancer 1.311 on Ubuntu 12.04, and uptodate modules from CPAN.

**Comment by bigpresh** [comment]
That's correct - supplying the config in config.yml tells the plugin how to behave, but doesn't actually enable it - you have to `use` it in the normal way as you discovered.

I'll review the POD to see if that isn't made clear.

**Comment by MagnusEnger** [comment]
Ah, I somehow got the impression that only the config was needed. But that might just be me being dim...

**Comment by garu** [comment]
It is indeed somewhat confusing. I added a small doc patch in #18 that should help!

**Comment by MagnusEnger** [comment]
Thanks for the clarification!
