### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by huguesmax** [bigpresh/Dancer-Plugin-NYTProf#15]
Hello David
small mistake
in your doc you indicate

plugins:
    NYTProf:
        profdir: '/tmp/profiledata'
        nytprofhtmlpath: '/usr/local/bin/nytprofhtml'

but in your code /usr/local/share/perl5/Dancer/Plugin/NYTProf.pm line 64
your code waitting  my $nytprofhtml_path = $setting->{nytprofhtml_path} with a underscore.

I've upate my setting to 
nytprofhtml_path: '/usr/local/bin/nytprofhtml'

**Comment by bigpresh** [comment]
Thanks for spotting & reporting that mistake!
