### ISSUE TITLE
Pod coverage test fails

### ISSUE THREAD

**Issue by eserte** [bigpresh/Dancer-Plugin-NYTProf#21]
With Dancer-Plugin-NYTProf-0.40:

```
#   Failed test 'Pod coverage on Dancer::Plugin::NYTProf'
#   at /opt/perl-5.10.1/lib/site_perl/5.10.1/Test/Pod/Coverage.pm line 133.
# Dancer::Plugin::NYTProf: requiring 'Dancer::Plugin::NYTProf' failed
# Looks like you failed 1 test of 1.
t/pod-coverage.t .. 
```

**Comment by bigpresh** [comment]
How strange - I ran the tests on my local machine and all passed fine - and they're passing in Travis too - https://travis-ci.org/bigpresh/Dancer-Plugin-NYTProf/builds/39305593 

Were there any other errors which might provide any further information?

**Comment by eserte** [comment]
I assume that this is the problematic part: `requiring 'Dancer::Plugin::NYTProf' failed`.
The failure happens on a machine where nytprofhtml is not installed for the system perl, but only in the custom perl's scriptdir (something like /opt/perl-5.X.Y/bin), which is not in the user's PATH. Probably you have to either skip the pod-coverage test like in the 00-load.t test, or maybe better, try to use the nytprofhtml from the correct scriptdir.

**Comment by bigpresh** [comment]
Ah, yes, you're right - it's almost certainly that it can't load the plugin if `nytprofhtml` isn't in the path.

Easy fix: the POD coverage/validity tests should really be release tests only, there's no point in them being run at install-time - so I'm moving them to `xt/`.

(This leaves the tests run at install-time, curently, as essentially "does it compile" - a big TODO is to write some proper tests - ideally something that spins up a test app, hits it with a few requests, checks the profile runs list is as expected etc...)
