### ISSUE TITLE
Need configuration option for path of "nytprof.out" file

### ISSUE THREAD

**Issue by nhooey** [bigpresh/Dancer-Plugin-NYTProf#5]
Right now the "nytprof.out" file gets written to the current working directory from where the Dancer application is run.

Could you make an option to configure where the file is written, or have it written to that other profile directory in the configuration?

**Comment by garu** [comment]
This issue has never been answered but at the moment there is a `profdir` that does precisely that.

@bigpresh it's probably safe to close this issue, right?

**Comment by bigpresh** [comment]
The profdir option sounds like it's exactly what you need.  Sorry I somehow missed this ticket for so long!

(I must configure something to whine at me if I have overdue stuff on GitHub...)
