### ISSUE TITLE
Ignores application path

### ISSUE THREAD

**Issue by boldra** [bigpresh/Dancer-Plugin-NYTProf#6]
My dancer application has an application path of 'app' (in apache config), so http://host:port/app/ is a request for '/'.  The generated nytprof files are correctly placed in /app/nytprof, but the index contains links to /nytprof/module instead of /app/nytprof/module (where the html files really are).

**Comment by bigpresh** [comment]
I think this should be fixed now as we use uri_base, so I'm going to mark this as closed (after a ridiculously long time - sorry...)

if you still experience the problem please re-open it!

**Comment by bigpresh** [comment]
Uh... I I said I was closing this, but it seems I didn't _actually_ do so :)
