### ISSUE TITLE
Some subroutines are sought in the wrong package

### ISSUE THREAD

**Issue by boldra** [bigpresh/Dancer-Plugin-NYTProf#7]
DBI::st::execute is listed on the index page as an expensive subroutine, but the link for this subroutine is of this form:
Dancer-Plugin-NYTProf-pm-1-line.html#DBI__st__execute

Which takes me to the Dancer::Plugin::NYTProf profiling page. Because there's no anchor matching DBI__st__execute on that page, I see the top of the page. Naturally there's  no 'DBI::st::execute' sub in the Dancer::Plugin::NYTProf package.

**Comment by bigpresh** [comment]
Sorry I somehow missed this one for so long!

Hmm - this sounds like an NYTProf bug, as it's in the actual output of NYTProf.

Do you still have this problem?

**Comment by bigpresh** [comment]
As this sounded like an NYTProf problem, not a problem with this plugin, I'm closing this bug.
